# Generated by Django 5.1.7 on 2025-03-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='названия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('video_file', models.FileField(upload_to='movies/', verbose_name='фильм')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
